services:
  cache:
    image: redis:7.4.1-bookworm
    ports:
      - "8379:6379"
    command: redis-server --save 60 1 --loglevel warning

  broker:
    image: apache/kafka-native:3.9.0
    ports:
      - "9092:9092"
    env_file: .env
    environment:
      # Configure listeners for both docker and host.
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # KRaft mode.
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication.
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPIC}:4:1"

  aggregates-db:
    image: postgres:17.4-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${AGGREGATES_DB}
      POSTGRES_USER: ${AGGREGATES_USER}
      POSTGRES_PASSWORD: ${AGGREGATES_PASSWORD}
    ports:
      - "8432:5432"

  aggregates-db-migrations:
    image: amacneil/dbmate:2.27
    env_file: .env
    environment:
      DBMATE_NO_DUMP_SCHEMA: true
      DATABASE_URL: "${AGGREGATES_DB_URL}?sslmode=disable"
      TEST_DATABASE_URL: "${AGGREGATES_TEST_DB_URL}?sslmode=disable"
    ports:
      - "8432:5432"
    depends_on:
      - aggregates-db
    volumes:
      - ./app/db:/db

  warehouse:
    image: clickhouse:25.1
    environment:
      CLICKHOUSE_DB: ${WAREHOUSE_DB}
      CLICKHOUSE_USER: ${WAREHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD}
    ports:
      - "9000:9000/tcp"
    volumes:
      - ./db/warehouse:/docker-entrypoint-initdb.d

  ingest-worker:
    build:
      context: ingest
      dockerfile: Dockerfile
    command: "src.main"
    env_file: .env
    environment:
      SCHEMAS_DIR: /worker/schemas/raw
    depends_on:
      - cache
      - broker
    volumes:
      - ./schemas:/worker/schemas

  raw-consumer:
    build:
      context: consume
      dockerfile: Dockerfile
    env_file: .env
    environment:
      CONSUMER_TYPE: "raw"
      CONSUMER_GROUP_ID: "raw-consumer"
      AGGREGATES_DB_URL: ""
      WAREHOUSE_URL: ${WAREHOUSE_URL_GO}
    depends_on:
      - broker
      - warehouse
    volumes:
      - ./data:/worker/data

  aggregates-consumer:
    build:
      context: consume
      dockerfile: Dockerfile
    env_file: .env
    environment:
      CONSUMER_TYPE: "aggregates"
      CONSUMER_GROUP_ID: "aggregates-consumer"
      WAREHOUSE_URL: ""
    depends_on:
      - app
      - broker

  app:
    build:
      context: app
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - aggregates-db
      - cache

  reconciliation-worker:
    build:
      context: reconcile
      dockerfile: Dockerfile
    env_file: .env
    environment:
      WAREHOUSE_URL: ${WAREHOUSE_URL_PY}
    depends_on:
      - app
      - warehouse
