create table warehouse.a311_cases (
    service_request_id Int32,
    requested_datetime DateTime,
    closed_date Nullable(DateTime),
    updated_datetime DateTime,
    status_description String,
    status_notes Nullable(String),
    agency_responsible String,
    service_name String,
    service_subtype String,
    service_details Nullable(String),
    address String,
    street Nullable(String),
    supervisor_district Nullable(Float32),
    neighborhoods_sffind_boundaries Nullable(String),
    analysis_neighborhood Nullable(String),
    police_district Nullable(String),
    lat Float32,
    long Float32,
    bos_2012 Nullable(Float32),
    source String,
    data_as_of DateTime,
    data_loaded_at DateTime,
)
engine = MergeTree()
primary key (service_request_id, data_as_of);

create table warehouse.fire_ems_calls (
    call_number String,
    unit_id String,
    incident_number String,
    call_type String,
    call_date DateTime,
    watch_date DateTime,
    received_dttm DateTime,
    entry_dttm DateTime,
    dispatch_dttm DateTime,
    response_dttm Nullable(DateTime),
    on_scene_dttm Nullable(DateTime),
    transport_dttm Nullable(DateTime),
    hospital_dttm Nullable(DateTime),
    call_final_disposition String,
    available_dttm Nullable(DateTime),
    address Nullable(String),
    city String,
    zipcode_of_incident String,
    battalion String,
    station_area String,
    box String,
    original_priority String,
    priority String,
    final_priority String,
    als_unit Nullable(Boolean),
    call_type_group Nullable(String),
    number_of_alarms UInt8,
    unit_type String,
    unit_sequence_in_call_dispatch Int8,
    fire_prevention_district String,
    supervisor_district String,
    neighborhood_analysis_boundaries Nullable(String),
    rowid String,
    lat Float32,
    long Float32,
    data_as_of DateTime,
    data_loaded_at DateTime,
)
engine = MergeTree()
primary key (incident_number, data_as_of);

create table warehouse.fire_incidents (
    incident_number String,
    exposure_number String,
    id String,
    address String,
    incident_date DateTime,
    call_number String,
    alarm_dttm DateTime,
    arrival_dttm DateTime,
    close_dttm DateTime,
    city String,
    zipcode Nullable(String),
    battalion String,
    station_area String,
    box Nullable(String),
    suppression_units String,
    suppression_personnel String,
    ems_units String,
    ems_personnel String,
    other_units String,
    other_personnel String,
    first_unit_on_scene Nullable(String),
    estimated_property_loss Nullable(String),
    estimated_contents_loss Nullable(String),
    fire_fatalities String,
    fire_injuries String,
    civilian_fatalities String,
    civilian_injuries String,
    number_of_alarms String,
    primary_situation String,
    mutual_aid String,
    action_taken_primary Nullable(String),
    action_taken_secondary Nullable(String),
    action_taken_other Nullable(String),
    detector_alerted_occupants Nullable(String),
    property_use Nullable(String),
    area_of_fire_origin Nullable(String),
    ignition_cause Nullable(String),
    ignition_factor_primary Nullable(String),
    ignition_factor_secondary Nullable(String),
    heat_source Nullable(String),
    item_first_ignited Nullable(String),
    human_factors_associated_with_ignition Nullable(String),
    structure_type Nullable(String),
    structure_status Nullable(String),
    floor_of_fire_origin Nullable(UInt8),
    fire_spread Nullable(String),
    no_flame_spread Nullable(String),
    number_of_floors_with_minimum_damage Nullable(String),
    number_of_floors_with_significant_damage Nullable(String),
    number_of_floors_with_heavy_damage Nullable(String),
    number_of_floors_with_extreme_damage Nullable(String),
    detectors_present Nullable(String),
    detector_operation Nullable(String),
    detector_effectiveness Nullable(String),
    detector_failure_reason Nullable(String),
    automatic_extinguishing_system_present Nullable(String),
    automatic_extinguishing_system_type Nullable(String),
    automatic_extinguishing_system_performance Nullable(String),
    automatic_extinguishing_system_failure_reason Nullable(String),
    number_of_sprinkler_heads_operating Nullable(String),
    supervisor_district Nullable(String),
    neighborhood_district Nullable(String),
    lat Float32,
    long Float32,
    data_as_of DateTime,
    data_loaded_at DateTime,
)
engine = MergeTree()
primary key (incident_number, data_as_of);

create table warehouse.police_incidents (
    incident_datetime DateTime,
    incident_date DateTime,
    incident_time String,
    incident_year String,
    incident_day_of_week String,
    report_datetime DateTime,
    row_id String,
    incident_id String,
    incident_number String,
    cad_number Nullable(String),
    report_type_code String,
    report_type_description String,
    file_online Nullable(Boolean),
    incident_code String,
    incident_category String,
    incident_subcategory String,
    incident_description String,
    resolution String,
    intersection Nullable(String),
    cnn Nullable(String),
    police_district String,
    analysis_neighborhood Nullable(String),
    supervisor_district Nullable(Float32),
    supervisor_district_2012 Nullable(Float32),
    latitude Nullable(Float32),
    longitude Nullable(Float32),
)
engine = MergeTree()
primary key (incident_number);

create table warehouse.traffic_crashes (
    unique_id String,
    cnn_intrsctn_fkey Nullable(String),
    cnn_sgmt_fkey Nullable(String),
    case_id_pkey String,
    tb_latitude Nullable(Float32),
    tb_longitude Nullable(Float32),
    geocode_source String,
    geocode_location String,
    collision_datetime DateTime,
    collision_date DateTime,
    collision_time Nullable(String),
    accident_year String,
    month String,
    day_of_week Nullable(String),
    time_cat Nullable(String),
    juris String,
    officer_id Nullable(String),
    reporting_district Nullable(String),
    beat_number Nullable(String),
    primary_rd String,
    secondary_rd Nullable(String),
    distance Nullable(Float32),
    direction String,
    weather_1 String,
    weather_2 Nullable(String),
    collision_severity String,
    type_of_collision String,
    mviw String,
    ped_action String,
    road_surface String,
    road_cond_1 String,
    road_cond_2 String,
    lighting String,
    control_device String,
    intersection String,
    vz_pcf_code Nullable(String),
    vz_pcf_group Nullable(String),
    vz_pcf_description String,
    vz_pcf_link Nullable(String),
    number_killed Nullable(UInt8),
    number_injured Nullable(UInt8),
    street_view Nullable(String),
    dph_col_grp String,
    dph_col_grp_description String,
    party_at_fault Nullable(String),
    party1_type String,
    party1_dir_of_travel Nullable(String),
    party1_move_pre_acc Nullable(String),
    party2_type Nullable(String),
    party2_dir_of_travel Nullable(String),
    party2_move_pre_acc Nullable(String),
    data_as_of DateTime,
    data_updated_at DateTime,
    data_loaded_at DateTime,
    lat Nullable(Float32),
    long Nullable(Float32),
    analysis_neighborhood Nullable(String),
    supervisor_district Nullable(String),
    police_district Nullable(String),
)
engine = MergeTree()
primary key (unique_id);
